# Generated by Django 4.2.3 on 2023-07-26 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_country_product_date_created_state_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='country',
            new_name='state',
        ),
    ]
