# Generated by Django 4.2.3 on 2023-08-10 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_product_description_alter_product_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsocialmedia',
            name='url',
            field=models.URLField(max_length=1000),
        ),
    ]
