# Generated by Django 4.2.3 on 2023-07-23 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('fullname', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=120)),
                ('ip_address', models.GenericIPAddressField()),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user.user')),
                ('otp_value', models.IntegerField()),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
